server:
  port: 9086
kafkaStream:
  bootStrapServer: localhost:9092
  applicationId: testStreams
  producerTopic: kafkaPocStreaming1Exchange
  consumerTopic: sampletest1
  groupEmailID: rsara@nisum.com
