server:
  port: 9086
kafkaStream:
  bootStrapServer: 137.117.10.35:9092
  applicationId: testStreams
  producerTopic: kafkaPocStreaming1Exchange
  consumerTopic: sampletest1
  groupEmailID: rsara@nisum.com


  
  
 