server:
  port: 8085
kafkaStream:
  bootStrapServer: localhost:9092
  applicationId: testStreams
  producerTopic: employee
  consumerTopic: emailemployee
  groupEmailID: kumarpasupuleti@gmail.com


  
  
 